apiVersion: v1
kind: Service
metadata:
  name: zk
  labels:
    app: zk
spec:
  ports:
    - name: zk
      port: 2181
  clusterIP: None
  selector:
    app: zk
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zookeeper
        imagePullPolicy: Always
        image: "zookeeper:3.7"
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: "256Mi"
            cpu: "0.5"
        ports:
          - containerPort: 2181
            name: zk
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "bin/zkCli.sh stat /zookeeper/config >/dev/null"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: zk-data
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: zk-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
